In [3]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [4]:
sentence='''The wind whispered through the tall trees.
The sun dipped behind the hills, casting long shadows across the quiet valley.
Birds fluttered above, their wings slicing the cool evening air.
A gentle stream trickled nearby, humming its ancient song.
A boy stood alone on the worn trail.
He stared ahead with both curiosity and hesitation.
His backpack was light, yet his heart felt heavy with the unknown.
Every step forward felt like a choice.
It was a silent commitment to change.
The world around him seemed alive, listening, waiting.
Though he didn’t know what lay ahead, he chose to move.'''

In [5]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([sentence])

In [6]:
tokenizer.word_index

{'the': 1,
 'a': 2,
 'he': 3,
 'ahead': 4,
 'with': 5,
 'his': 6,
 'was': 7,
 'felt': 8,
 'to': 9,
 'wind': 10,
 'whispered': 11,
 'through': 12,
 'tall': 13,
 'trees': 14,
 'sun': 15,
 'dipped': 16,
 'behind': 17,
 'hills': 18,
 'casting': 19,
 'long': 20,
 'shadows': 21,
 'across': 22,
 'quiet': 23,
 'valley': 24,
 'birds': 25,
 'fluttered': 26,
 'above': 27,
 'their': 28,
 'wings': 29,
 'slicing': 30,
 'cool': 31,
 'evening': 32,
 'air': 33,
 'gentle': 34,
 'stream': 35,
 'trickled': 36,
 'nearby': 37,
 'humming': 38,
 'its': 39,
 'ancient': 40,
 'song': 41,
 'boy': 42,
 'stood': 43,
 'alone': 44,
 'on': 45,
 'worn': 46,
 'trail': 47,
 'stared': 48,
 'both': 49,
 'curiosity': 50,
 'and': 51,
 'hesitation': 52,
 'backpack': 53,
 'light': 54,
 'yet': 55,
 'heart': 56,
 'heavy': 57,
 'unknown': 58,
 'every': 59,
 'step': 60,
 'forward': 61,
 'like': 62,
 'choice': 63,
 'it': 64,
 'silent': 65,
 'commitment': 66,
 'change': 67,
 'world': 68,
 'around': 69,
 'him': 70,
 'seemed': 71,
 'a

In [7]:
for sentences in sentence.split('\n'):
    print(sentences)

The wind whispered through the tall trees.
The sun dipped behind the hills, casting long shadows across the quiet valley.
Birds fluttered above, their wings slicing the cool evening air.
A gentle stream trickled nearby, humming its ancient song.
A boy stood alone on the worn trail.
He stared ahead with both curiosity and hesitation.
His backpack was light, yet his heart felt heavy with the unknown.
Every step forward felt like a choice.
It was a silent commitment to change.
The world around him seemed alive, listening, waiting.
Though he didn’t know what lay ahead, he chose to move.


In [8]:
for sentences in sentence.split('\n'):
    print(tokenizer.texts_to_sequences([sentences])[0])

[1, 10, 11, 12, 1, 13, 14]
[1, 15, 16, 17, 1, 18, 19, 20, 21, 22, 1, 23, 24]
[25, 26, 27, 28, 29, 30, 1, 31, 32, 33]
[2, 34, 35, 36, 37, 38, 39, 40, 41]
[2, 42, 43, 44, 45, 1, 46, 47]
[3, 48, 4, 5, 49, 50, 51, 52]
[6, 53, 7, 54, 55, 6, 56, 8, 57, 5, 1, 58]
[59, 60, 61, 8, 62, 2, 63]
[64, 7, 2, 65, 66, 9, 67]
[1, 68, 69, 70, 71, 72, 73, 74]
[75, 3, 76, 77, 78, 79, 4, 3, 80, 9, 81]


In [9]:
input_sequences=[]
for sentences in sentence.split('\n'):
    tokenized_sentence = tokenizer.texts_to_sequences([sentences])[0]

    for i in range(1,len(tokenized_sentence)):
       input_sequences.append(tokenized_sentence[:i+1])
    

In [10]:
print(input_sequences)

[[1, 10], [1, 10, 11], [1, 10, 11, 12], [1, 10, 11, 12, 1], [1, 10, 11, 12, 1, 13], [1, 10, 11, 12, 1, 13, 14], [1, 15], [1, 15, 16], [1, 15, 16, 17], [1, 15, 16, 17, 1], [1, 15, 16, 17, 1, 18], [1, 15, 16, 17, 1, 18, 19], [1, 15, 16, 17, 1, 18, 19, 20], [1, 15, 16, 17, 1, 18, 19, 20, 21], [1, 15, 16, 17, 1, 18, 19, 20, 21, 22], [1, 15, 16, 17, 1, 18, 19, 20, 21, 22, 1], [1, 15, 16, 17, 1, 18, 19, 20, 21, 22, 1, 23], [1, 15, 16, 17, 1, 18, 19, 20, 21, 22, 1, 23, 24], [25, 26], [25, 26, 27], [25, 26, 27, 28], [25, 26, 27, 28, 29], [25, 26, 27, 28, 29, 30], [25, 26, 27, 28, 29, 30, 1], [25, 26, 27, 28, 29, 30, 1, 31], [25, 26, 27, 28, 29, 30, 1, 31, 32], [25, 26, 27, 28, 29, 30, 1, 31, 32, 33], [2, 34], [2, 34, 35], [2, 34, 35, 36], [2, 34, 35, 36, 37], [2, 34, 35, 36, 37, 38], [2, 34, 35, 36, 37, 38, 39], [2, 34, 35, 36, 37, 38, 39, 40], [2, 34, 35, 36, 37, 38, 39, 40, 41], [2, 42], [2, 42, 43], [2, 42, 43, 44], [2, 42, 43, 44, 45], [2, 42, 43, 44, 45, 1], [2, 42, 43, 44, 45, 1, 46], [2

In [11]:
max_len1 = max([len(x) for x in input_sequences])
print(max_len1)

13


In [12]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences, maxlen =max_len1, padding='pre')

In [13]:
padded_input_sequences

array([[ 0,  0,  0, ...,  0,  1, 10],
       [ 0,  0,  0, ...,  1, 10, 11],
       [ 0,  0,  0, ..., 10, 11, 12],
       ...,
       [ 0,  0,  0, ...,  4,  3, 80],
       [ 0,  0,  0, ...,  3, 80,  9],
       [ 0,  0, 75, ..., 80,  9, 81]], dtype=int32)

In [14]:
X=padded_input_sequences[:,:-1]
X

array([[ 0,  0,  0, ...,  0,  0,  1],
       [ 0,  0,  0, ...,  0,  1, 10],
       [ 0,  0,  0, ...,  1, 10, 11],
       ...,
       [ 0,  0,  0, ..., 79,  4,  3],
       [ 0,  0,  0, ...,  4,  3, 80],
       [ 0,  0, 75, ...,  3, 80,  9]], dtype=int32)

In [15]:
y=padded_input_sequences[:,-1]
y

array([10, 11, 12,  1, 13, 14, 15, 16, 17,  1, 18, 19, 20, 21, 22,  1, 23,
       24, 26, 27, 28, 29, 30,  1, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45,  1, 46, 47, 48,  4,  5, 49, 50, 51, 52, 53,  7,
       54, 55,  6, 56,  8, 57,  5,  1, 58, 60, 61,  8, 62,  2, 63,  7,  2,
       65, 66,  9, 67, 68, 69, 70, 71, 72, 73, 74,  3, 76, 77, 78, 79,  4,
        3, 80,  9, 81], dtype=int32)

In [16]:
X.shape

(89, 12)

In [17]:
y.shape

(89,)

In [18]:
from tensorflow.keras.utils import to_categorical
y= to_categorical(y,num_classes=82)

In [19]:
y.shape
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [20]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [21]:
model= Sequential()
model.add(Embedding(82,100,input_length=13))
model.add(LSTM(150))
model.add(Dense(82,activation='softmax'))

c:\Users\acer\python workspace\allvenv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [22]:
model.build(input_shape=(None, 13))
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 13, 100)        │         8,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 150)            │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 82)             │        12,382 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 171,182 (668.68 KB)

 Trainable params: 171,182 (668.68 KB)

 Non-trainable params: 0 (0.00 B)

In [23]:
model.fit(X,y,epochs=150)

Epoch 1/150
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.0615 - loss: 4.4080
Epoch 2/150
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.0845 - loss: 4.3961
Epoch 3/150
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.0571 - loss: 4.3850
Epoch 4/150
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.0611 - loss: 4.3720
Epoch 5/150
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.0689 - loss: 4.3530
Epoch 6/150
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.0611 - loss: 4.3206
Epoch 7/150
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.0806 - loss: 4.2555
Epoch 8/150
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.0571 - loss: 4.2329
Epoch 9/150
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.0728 - loss: 4.2339
Epoch 10/150
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.0532 - loss: 4.1931
Epoch 11/150
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.0571 - loss: 4.1417
Epoch 12/150
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.0650 - lo

In [ ]:
#predicting the next word
import time
import numpy as np
text= "It"
for i in range(5):
    #tokenize
    token_text= tokenizer.texts_to_sequences([text])[0]
    #padding
    padded_token_text= pad_sequences([token_text],maxlen=13, padding='pre')
    #predict
    pos= np.argmax(model.predict(padded_token_text))

    for word, index in tokenizer.word_index.items():
        if index == pos:
            text = text + " " + word
            print(text)
            time.sleep(2)



1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step
It was
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
It was a
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
It was a silent
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
It was a silent commitment
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
It was a silent commitment commitment
