In [77]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [78]:
sentence='''The wind whispered through the tall trees.
The sun dipped behind the hills, casting long shadows across the quiet valley.
Birds fluttered above, their wings slicing the cool evening air.
A gentle stream trickled nearby, humming its ancient song.
A boy stood alone on the worn trail.
He stared ahead with both curiosity and hesitation.
His backpack was light, yet his heart felt heavy with the unknown.
Every step forward felt like a choice.
It was a silent commitment to change.
The world around him seemed alive, listening, waiting.
Though he didn’t know what lay ahead, he chose to move.'''

In [79]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([sentence])

In [80]:
tokenizer.word_index

{'the': 1,
 'a': 2,
 'he': 3,
 'ahead': 4,
 'with': 5,
 'his': 6,
 'was': 7,
 'felt': 8,
 'to': 9,
 'wind': 10,
 'whispered': 11,
 'through': 12,
 'tall': 13,
 'trees': 14,
 'sun': 15,
 'dipped': 16,
 'behind': 17,
 'hills': 18,
 'casting': 19,
 'long': 20,
 'shadows': 21,
 'across': 22,
 'quiet': 23,
 'valley': 24,
 'birds': 25,
 'fluttered': 26,
 'above': 27,
 'their': 28,
 'wings': 29,
 'slicing': 30,
 'cool': 31,
 'evening': 32,
 'air': 33,
 'gentle': 34,
 'stream': 35,
 'trickled': 36,
 'nearby': 37,
 'humming': 38,
 'its': 39,
 'ancient': 40,
 'song': 41,
 'boy': 42,
 'stood': 43,
 'alone': 44,
 'on': 45,
 'worn': 46,
 'trail': 47,
 'stared': 48,
 'both': 49,
 'curiosity': 50,
 'and': 51,
 'hesitation': 52,
 'backpack': 53,
 'light': 54,
 'yet': 55,
 'heart': 56,
 'heavy': 57,
 'unknown': 58,
 'every': 59,
 'step': 60,
 'forward': 61,
 'like': 62,
 'choice': 63,
 'it': 64,
 'silent': 65,
 'commitment': 66,
 'change': 67,
 'world': 68,
 'around': 69,
 'him': 70,
 'seemed': 71,
 'a

In [81]:
for sentences in sentence.split('\n'):
    print(sentences)

The wind whispered through the tall trees.
The sun dipped behind the hills, casting long shadows across the quiet valley.
Birds fluttered above, their wings slicing the cool evening air.
A gentle stream trickled nearby, humming its ancient song.
A boy stood alone on the worn trail.
He stared ahead with both curiosity and hesitation.
His backpack was light, yet his heart felt heavy with the unknown.
Every step forward felt like a choice.
It was a silent commitment to change.
The world around him seemed alive, listening, waiting.
Though he didn’t know what lay ahead, he chose to move.


In [82]:
for sentences in sentence.split('\n'):
    print(tokenizer.texts_to_sequences([sentences])[0])

[1, 10, 11, 12, 1, 13, 14]
[1, 15, 16, 17, 1, 18, 19, 20, 21, 22, 1, 23, 24]
[25, 26, 27, 28, 29, 30, 1, 31, 32, 33]
[2, 34, 35, 36, 37, 38, 39, 40, 41]
[2, 42, 43, 44, 45, 1, 46, 47]
[3, 48, 4, 5, 49, 50, 51, 52]
[6, 53, 7, 54, 55, 6, 56, 8, 57, 5, 1, 58]
[59, 60, 61, 8, 62, 2, 63]
[64, 7, 2, 65, 66, 9, 67]
[1, 68, 69, 70, 71, 72, 73, 74]
[75, 3, 76, 77, 78, 79, 4, 3, 80, 9, 81]


In [83]:
input_sequences=[]
for sentences in sentence.split('\n'):
    tokenized_sentence = tokenizer.texts_to_sequences([sentences])[0]

    for i in range(1,len(tokenized_sentence)):
       input_sequences.append(tokenized_sentence[:i+1])
    

In [84]:
print(input_sequences)

[[1, 10], [1, 10, 11], [1, 10, 11, 12], [1, 10, 11, 12, 1], [1, 10, 11, 12, 1, 13], [1, 10, 11, 12, 1, 13, 14], [1, 15], [1, 15, 16], [1, 15, 16, 17], [1, 15, 16, 17, 1], [1, 15, 16, 17, 1, 18], [1, 15, 16, 17, 1, 18, 19], [1, 15, 16, 17, 1, 18, 19, 20], [1, 15, 16, 17, 1, 18, 19, 20, 21], [1, 15, 16, 17, 1, 18, 19, 20, 21, 22], [1, 15, 16, 17, 1, 18, 19, 20, 21, 22, 1], [1, 15, 16, 17, 1, 18, 19, 20, 21, 22, 1, 23], [1, 15, 16, 17, 1, 18, 19, 20, 21, 22, 1, 23, 24], [25, 26], [25, 26, 27], [25, 26, 27, 28], [25, 26, 27, 28, 29], [25, 26, 27, 28, 29, 30], [25, 26, 27, 28, 29, 30, 1], [25, 26, 27, 28, 29, 30, 1, 31], [25, 26, 27, 28, 29, 30, 1, 31, 32], [25, 26, 27, 28, 29, 30, 1, 31, 32, 33], [2, 34], [2, 34, 35], [2, 34, 35, 36], [2, 34, 35, 36, 37], [2, 34, 35, 36, 37, 38], [2, 34, 35, 36, 37, 38, 39], [2, 34, 35, 36, 37, 38, 39, 40], [2, 34, 35, 36, 37, 38, 39, 40, 41], [2, 42], [2, 42, 43], [2, 42, 43, 44], [2, 42, 43, 44, 45], [2, 42, 43, 44, 45, 1], [2, 42, 43, 44, 45, 1, 46], [2

In [85]:
max_len1 = max([len(x) for x in input_sequences])
print(max_len1)

13


In [86]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences, maxlen =max_len1, padding='pre')

In [87]:
padded_input_sequences

array([[ 0,  0,  0, ...,  0,  1, 10],
       [ 0,  0,  0, ...,  1, 10, 11],
       [ 0,  0,  0, ..., 10, 11, 12],
       ...,
       [ 0,  0,  0, ...,  4,  3, 80],
       [ 0,  0,  0, ...,  3, 80,  9],
       [ 0,  0, 75, ..., 80,  9, 81]], dtype=int32)

In [88]:
X=padded_input_sequences[:,:-1]
X

array([[ 0,  0,  0, ...,  0,  0,  1],
       [ 0,  0,  0, ...,  0,  1, 10],
       [ 0,  0,  0, ...,  1, 10, 11],
       ...,
       [ 0,  0,  0, ..., 79,  4,  3],
       [ 0,  0,  0, ...,  4,  3, 80],
       [ 0,  0, 75, ...,  3, 80,  9]], dtype=int32)

In [89]:
y=padded_input_sequences[:,-1]
y

array([10, 11, 12,  1, 13, 14, 15, 16, 17,  1, 18, 19, 20, 21, 22,  1, 23,
       24, 26, 27, 28, 29, 30,  1, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45,  1, 46, 47, 48,  4,  5, 49, 50, 51, 52, 53,  7,
       54, 55,  6, 56,  8, 57,  5,  1, 58, 60, 61,  8, 62,  2, 63,  7,  2,
       65, 66,  9, 67, 68, 69, 70, 71, 72, 73, 74,  3, 76, 77, 78, 79,  4,
        3, 80,  9, 81], dtype=int32)

In [90]:
X.shape

(89, 12)

In [91]:
y.shape

(89,)

In [92]:
from tensorflow.keras.utils import to_categorical
y= to_categorical(y,num_classes=82)

In [93]:
y.shape
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [94]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [100]:
model= Sequential()
model.add(Embedding(82,100,input_length=13))
model.add(LSTM(150))
model.add(Dense(82,activation='softmax'))

In [101]:
model.build(input_shape=(None, 13))
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 13, 100)        │         8,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_3 (LSTM)                   │ (None, 150)            │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 82)             │        12,382 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 171,182 (668.68 KB)

 Trainable params: 171,182 (668.68 KB)

 Non-trainable params: 0 (0.00 B)

In [103]:
model.fit(X,y,epochs=150)

Epoch 1/150
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8254 - loss: 1.2386
Epoch 2/150
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8198 - loss: 1.1892
Epoch 3/150
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8540 - loss: 1.1733
Epoch 4/150
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8948 - loss: 1.0988
Epoch 5/150
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8835 - loss: 1.0692
Epoch 6/150
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8835 - loss: 1.0228
Epoch 7/150
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8774 - loss: 1.0308
Epoch 8/150
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9182 - loss: 0.9775
Epoch 9/150
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.8718 - loss: 0.9657
Epoch 10/150
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9216 - loss: 0.9378
Epoch 11/150
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9009 - loss: 0.8866
Epoch 12/150
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9333 - lo

In [ ]:
import time
import numpy as np
text= "around"
for i in range(5):
    #tokenize
    token_text= tokenizer.texts_to_sequences([text])[0]
    #padding
    padded_token_text= pad_sequences([token_text],maxlen=13, padding='pre')
    #predict
    pos= np.argmax(model.predict(padded_token_text))

    for word, index in tokenizer.word_index.items():
        if index == pos:
            text = text + " " + word
            print(text)
            time.sleep(2)



1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
around was
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
around was was
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
around was was a
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
around was was a silent
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
around was was a silent commitment


: 